name: docker

on:
  workflow_dispatch:
  push:
    # tags:
    #   - "v*"

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            "registry.cn-chengdu.aliyuncs.com/wizz-project/xdu-partner"
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/login-action
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: registry.cn-chengdu.aliyuncs.com
          username: ${{ secrets.ALI_REGISTRY_USERNAME }}
          password: ${{ secrets.ALI_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          # context: ./
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # file: "./game/Dockerfile"

      - name: Notify Wizz Op
        run: |
          curl -X POST -H 'Content-Type: application/json' https://wizz-op.be.wizzstudio.com:30000/api/execute -d '{"username": "qizhenxin","password": "'"$OP_PASSWORD"'","script": "update-xdu-partner"}'
        env:
          OP_PASSWORD: ${{ secrets.OP_PASSWORD }}
